baseURL = 'https://allatrendorseg.github.io'
title = 'Állatrendőrség Alapítvány'

theme = "ananke"

enableEmoji = true

DefaultContentLanguage = "hu"
SectionPagesMenu = "main"

# this is set low for demonstrating with dummy content. Set to a higher number
pagination.pagerSize = 1

googleAnalytics = "G-HS836SY8RX"
enableRobotsTXT = true


[params]
favicon = "images/logo-smallest.png"
site_logo = "images/logo-200.png"
recent_posts_number = 1
background_color_class = "bg-dark-gray"
description = "Charity Organization"

[params.ananke.social.follow]
new_window_icon = true
networks = ["facebook", "instagram", "tiktok", "youtube"]

[params.ananke.social.facebook]
label = "Facebook"
profilelink = "https://www.facebook.com/allatrendorseg2013"

[params.ananke.social.instagram]
label = "Instagram"
profilelink = "https://www.instagram.com/allatrendorseg_alapitvany"

[params.ananke.social.tiktok]
label = "TikTok"
profilelink = "https://www.tiktok.com/@allatrendorsegalapitvany"

[params.ananke.social.youtube]
label = "YouTube"
profilelink = "https://www.youtube.com/@allatrendorsegalapitvany2841"

[languages]

[languages.EN]
title = "Animal Police Organization"
weight = 2
contentDir = "content/en"

[languages.HU]
title = "Állatrendőrség Alapítvány"
weight = 1
contentDir = "content/hu"
